AWSTemplateFormatVersion : '2010-09-09'

Description: A hello world application.
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/hello
      Runtime: go1.x
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /hello
            Method: post

  PutItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/putItem
      Runtime: go1.x
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /putItem
            Method: post 
      Timeout: 3


  ScanAllFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/scanAll
      Runtime: go1.x
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /scan
            Method: get 
      Timeout: 3

  GetItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/getItem
      Runtime: go1.x
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /getItem/{Id}
            Method: get 
      Timeout: 3

  DeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/delete
      Runtime: go1.x
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /delete
            Method: post
      Timeout: 3

  MockErrorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/mock_error
      Runtime: go1.x
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /mock_error
            Method: get
      Timeout: 3

  BookTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: Book
      AttributeDefinitions: 
        - AttributeName: Id
          AttributeType: S
      KeySchema: 
        - AttributeName: Id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE