AWSTemplateFormatVersion : '2010-09-09'

Description: A hello world application.
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/hello
      Runtime: go1.x
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /hello
            Method: post

  CreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/create
      Runtime: go1.x
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /create
            Method: post 
      Timeout: 3


  ScanFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/scan
      Runtime: go1.x
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /scan
            Method: get 
      Timeout: 3

  BookTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: Book
      AttributeDefinitions: 
        - AttributeName: Id
          AttributeType: S
      KeySchema: 
        - AttributeName: Id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE