name: golang CI

on: [push]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      options: --user 0
    defaults:
      run:
        shell: bash
    steps:
      - name: Print dir
        run: ls

      - name: Checkout sls-go-mod
        uses: actions/checkout@v2

      - name: Update ubuntu
        run: apt-get update

      - name: Install curl, jq, make, zip, ping
        run:  apt-get -qq -y install curl jq build-essential zip iputils-ping

      - name: Install docker-compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose \
          && chmod +x /usr/local/bin/docker-compose

      # - name: install aws-cli
      #   run: |
      #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
      #     && unzip -qq awscliv2.zip \
      #     && ./aws/install
      # - name: Print dir
      #   run: ls
      # - name: Delete downloaded aws files
      #   run: rm -rf aws && rm -rf awscliv2.zip

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.6'
      - name: Install Go modules
        run: go mod download

      - name: Start db
        run: make db-start

      - name: Ping db
        run: curl http://host.docker.internal:18000

      - name: Chmod seed files
        run: chmod +x ./src/data/seed/create_book_table.json && chmod +x ./src/data/seed/seed_book_table.json

      - name: Create table
        run: make db-create-table

      - name: Seed table
        run: make db-seed-data

      - name: Run test
        run: make test

      - name: Run lint
        run: make lint-install && make lint


